# Generated by Django 5.1.4 on 2025-05-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_grouppost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouppost',
            options={},
        ),
        migrations.AddField(
            model_name='grouppost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='group_posts/'),
        ),
    ]
