# Generated by Django 5.1.4 on 2025-03-29 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_requests', '0003_helprequest_applicants_helprequest_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helprequest',
            name='user',
        ),
    ]
