# Generated by Django 5.1.4 on 2025-05-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_requests', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
