# Generated by Django 5.1.4 on 2025-05-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_requests', '0007_helpapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
