# Generated by Django 5.1.4 on 2025-04-16 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='txn_id',
            new_name='pidx',
        ),
    ]
