# Generated by Django 5.1.4 on 2025-05-21 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_inkinddonation'),
        ('groups', '0002_grouppost'),
        ('help_requests', '0006_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='inkinddonation',
            old_name='item_name',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='group',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='help_request',
        ),
        migrations.AddField(
            model_name='inkinddonation',
            name='drop_off_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DonationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('help_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='help_requests.helprequest')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donation.donationcampaign'),
        ),
    ]
